/* 
 * @(#)Dns.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-notificaions", revision: "2018-06-06".
 */

package com.nokia.eml.yang.openconfigNotificaions.systemNotification.update.system;

import com.nokia.eml.yang.openconfigNotificaions.systemNotification.update.system.dns.Config;
import com.nokia.eml.yang.openconfigNotificaions.systemNotification.update.system.dns.HostEntries;
import com.nokia.eml.yang.openconfigNotificaions.systemNotification.update.system.dns.Servers;
import com.nokia.eml.yang.openconfigNotificaions.systemNotification.update.system.dns.State;
import com.nokia.eml.yang.openconfigSystem.OcSys;
import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.NodeSet;
import com.tailf.jnc.YangElement;

/**
 * This class represents an element from 
 * the namespace http://openconfig.net/yang/openconfig-notificaions
 * generated to "src/com/nokia/eml/yang/openconfigNotificaions/systemNotification/update/system/dns"
 * <p>
 * See line 421 in
 * /root/nokia-yang/system/openconfig-system.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class Dns extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Field for child container "config".
     */
    public Config config = null;

    /**
     * Field for child container "state".
     */
    public State state = null;

    /**
     * Field for child container "servers".
     */
    public Servers servers = null;

    /**
     * Field for child container "host-entries".
     */
    public HostEntries hostEntries = null;

    /**
     * Constructor for an empty Dns object.
     */
    public Dns() {
        super(OcSys.NAMESPACE, "dns");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Dns clone() {
        return (Dns)cloneContent(new Dns());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Dns cloneShallow() {
        return (Dns)cloneShallowContent(new Dns());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "config",
            "state",
            "servers",
            "host-entries",
        };
    }

    /* Access methods for container child: "config". */

    /**
     * Adds container entry "config", using an existing object.
     * @param config The object to add.
     * @return The added child.
     */
    public Config addConfig(Config config) throws JNCException {
        this.config = config;
        insertChild(config, childrenNames());
        return config;
    }

    /**
     * Adds container entry "config".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Config addConfig() throws JNCException {
        Config config = new Config();
        this.config = config;
        insertChild(config, childrenNames());
        return config;
    }

    /**
     * Deletes container entry "config".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteConfig() throws JNCException {
        this.config = null;
        String path = "config";
        return delete(path);
    }

    /* Access methods for container child: "state". */

    /**
     * Adds container entry "state", using an existing object.
     * @param state The object to add.
     * @return The added child.
     */
    public State addState(State state) throws JNCException {
        this.state = state;
        insertChild(state, childrenNames());
        return state;
    }

    /**
     * Adds container entry "state".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public State addState() throws JNCException {
        State state = new State();
        this.state = state;
        insertChild(state, childrenNames());
        return state;
    }

    /**
     * Deletes container entry "state".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteState() throws JNCException {
        this.state = null;
        String path = "state";
        return delete(path);
    }

    /* Access methods for container child: "servers". */

    /**
     * Adds container entry "servers", using an existing object.
     * @param servers The object to add.
     * @return The added child.
     */
    public Servers addServers(Servers servers) throws JNCException {
        this.servers = servers;
        insertChild(servers, childrenNames());
        return servers;
    }

    /**
     * Adds container entry "servers".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Servers addServers() throws JNCException {
        Servers servers = new Servers();
        this.servers = servers;
        insertChild(servers, childrenNames());
        return servers;
    }

    /**
     * Deletes container entry "servers".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteServers() throws JNCException {
        this.servers = null;
        String path = "servers";
        return delete(path);
    }

    /* Access methods for container child: "host-entries". */

    /**
     * Adds container entry "hostEntries", using an existing object.
     * @param hostEntries The object to add.
     * @return The added child.
     */
    public HostEntries addHostEntries(HostEntries hostEntries)
            throws JNCException {
        this.hostEntries = hostEntries;
        insertChild(hostEntries, childrenNames());
        return hostEntries;
    }

    /**
     * Adds container entry "hostEntries".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public HostEntries addHostEntries() throws JNCException {
        HostEntries hostEntries = new HostEntries();
        this.hostEntries = hostEntries;
        insertChild(hostEntries, childrenNames());
        return hostEntries;
    }

    /**
     * Deletes container entry "hostEntries".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteHostEntries() throws JNCException {
        this.hostEntries = null;
        String path = "host-entries";
        return delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
        if (child instanceof Config) config = (Config)child;
        else if (child instanceof State) state = (State)child;
        else if (child instanceof Servers) servers = (Servers)child;
        else if (child instanceof HostEntries) hostEntries = (HostEntries)child;
    }

}
