/* 
 * @(#)Counters.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-lldp", revision: "2016-05-16".
 */

package com.nokia.eml.yang.openconfigLldp.lldp.state;

import com.nokia.eml.yang.ietfYangTypes.Counter64;
import com.nokia.eml.yang.ietfYangTypes.DateAndTime;
import com.nokia.eml.yang.openconfigLldp.OcLldp;
import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangElement;

import java.math.BigInteger;

/**
 * This class represents an element from 
 * the namespace http://openconfig.net/yang/lldp
 * generated to "src/com/nokia/eml/yang/openconfigLldp/lldp/state/counters"
 * <p>
 * See line 589 in
 * /root/nokia-yang/lldp/openconfig-lldp.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class Counters extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Counters object.
     */
    public Counters() {
        super(OcLldp.NAMESPACE, "counters");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Counters clone() {
        return (Counters)cloneContent(new Counters());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Counters cloneShallow() {
        return (Counters)cloneShallowContent(new Counters());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "frame-in",
            "frame-out",
            "frame-error-in",
            "frame-discard",
            "tlv-discard",
            "tlv-unknown",
            "last-clear",
            "tlv-accepted",
            "entries-aged-out",
        };
    }

    /* Access methods for optional leaf child: "frame-in". */

    /**
     * Gets the value for child leaf "frame-in".
     * @return The value of the leaf.
     */
    public Counter64 getFrameInValue() throws JNCException {
        return (Counter64)getValue("frame-in");
    }

    /**
     * Sets the value for child leaf "frame-in",
     * using a JNC type value.
     * @param frameInValue The value to set.
     * @param frameInValue used during instantiation.
     */
    public void setFrameInValue(Counter64 frameInValue) throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-in",
            frameInValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "frame-in",
     * using Java primitive values.
     * @param frameInValue used during instantiation.
     */
    public void setFrameInValue(BigInteger frameInValue) throws JNCException {
        setFrameInValue(new Counter64(frameInValue));
    }

    /**
     * Sets the value for child leaf "frame-in",
     * using a String value.
     * @param frameInValue used during instantiation.
     */
    public void setFrameInValue(String frameInValue) throws JNCException {
        setFrameInValue(new Counter64(frameInValue));
    }

    /**
     * Unsets the value for child leaf "frame-in".
     */
    public void unsetFrameInValue() throws JNCException {
        delete("frame-in");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "frame-in" leaf will not have a value.
     */
    public void addFrameIn() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-in",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "frame-in" with operation "replace".
     */
    public void markFrameInReplace() throws JNCException {
        markLeafReplace("frameIn");
    }

    /**
     * Marks the leaf "frame-in" with operation "merge".
     */
    public void markFrameInMerge() throws JNCException {
        markLeafMerge("frameIn");
    }

    /**
     * Marks the leaf "frame-in" with operation "create".
     */
    public void markFrameInCreate() throws JNCException {
        markLeafCreate("frameIn");
    }

    /**
     * Marks the leaf "frame-in" with operation "delete".
     */
    public void markFrameInDelete() throws JNCException {
        markLeafDelete("frameIn");
    }

    /* Access methods for optional leaf child: "frame-out". */

    /**
     * Gets the value for child leaf "frame-out".
     * @return The value of the leaf.
     */
    public Counter64 getFrameOutValue() throws JNCException {
        return (Counter64)getValue("frame-out");
    }

    /**
     * Sets the value for child leaf "frame-out",
     * using a JNC type value.
     * @param frameOutValue The value to set.
     * @param frameOutValue used during instantiation.
     */
    public void setFrameOutValue(Counter64 frameOutValue) throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-out",
            frameOutValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "frame-out",
     * using Java primitive values.
     * @param frameOutValue used during instantiation.
     */
    public void setFrameOutValue(BigInteger frameOutValue) throws JNCException {
        setFrameOutValue(new Counter64(frameOutValue));
    }

    /**
     * Sets the value for child leaf "frame-out",
     * using a String value.
     * @param frameOutValue used during instantiation.
     */
    public void setFrameOutValue(String frameOutValue) throws JNCException {
        setFrameOutValue(new Counter64(frameOutValue));
    }

    /**
     * Unsets the value for child leaf "frame-out".
     */
    public void unsetFrameOutValue() throws JNCException {
        delete("frame-out");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "frame-out" leaf will not have a value.
     */
    public void addFrameOut() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-out",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "frame-out" with operation "replace".
     */
    public void markFrameOutReplace() throws JNCException {
        markLeafReplace("frameOut");
    }

    /**
     * Marks the leaf "frame-out" with operation "merge".
     */
    public void markFrameOutMerge() throws JNCException {
        markLeafMerge("frameOut");
    }

    /**
     * Marks the leaf "frame-out" with operation "create".
     */
    public void markFrameOutCreate() throws JNCException {
        markLeafCreate("frameOut");
    }

    /**
     * Marks the leaf "frame-out" with operation "delete".
     */
    public void markFrameOutDelete() throws JNCException {
        markLeafDelete("frameOut");
    }

    /* Access methods for optional leaf child: "frame-error-in". */

    /**
     * Gets the value for child leaf "frame-error-in".
     * @return The value of the leaf.
     */
    public Counter64 getFrameErrorInValue() throws JNCException {
        return (Counter64)getValue("frame-error-in");
    }

    /**
     * Sets the value for child leaf "frame-error-in",
     * using a JNC type value.
     * @param frameErrorInValue The value to set.
     * @param frameErrorInValue used during instantiation.
     */
    public void setFrameErrorInValue(Counter64 frameErrorInValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-error-in",
            frameErrorInValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "frame-error-in",
     * using Java primitive values.
     * @param frameErrorInValue used during instantiation.
     */
    public void setFrameErrorInValue(BigInteger frameErrorInValue)
            throws JNCException {
        setFrameErrorInValue(new Counter64(frameErrorInValue));
    }

    /**
     * Sets the value for child leaf "frame-error-in",
     * using a String value.
     * @param frameErrorInValue used during instantiation.
     */
    public void setFrameErrorInValue(String frameErrorInValue)
            throws JNCException {
        setFrameErrorInValue(new Counter64(frameErrorInValue));
    }

    /**
     * Unsets the value for child leaf "frame-error-in".
     */
    public void unsetFrameErrorInValue() throws JNCException {
        delete("frame-error-in");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "frame-error-in" leaf will not have a value.
     */
    public void addFrameErrorIn() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-error-in",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "frame-error-in" with operation "replace".
     */
    public void markFrameErrorInReplace() throws JNCException {
        markLeafReplace("frameErrorIn");
    }

    /**
     * Marks the leaf "frame-error-in" with operation "merge".
     */
    public void markFrameErrorInMerge() throws JNCException {
        markLeafMerge("frameErrorIn");
    }

    /**
     * Marks the leaf "frame-error-in" with operation "create".
     */
    public void markFrameErrorInCreate() throws JNCException {
        markLeafCreate("frameErrorIn");
    }

    /**
     * Marks the leaf "frame-error-in" with operation "delete".
     */
    public void markFrameErrorInDelete() throws JNCException {
        markLeafDelete("frameErrorIn");
    }

    /* Access methods for optional leaf child: "frame-discard". */

    /**
     * Gets the value for child leaf "frame-discard".
     * @return The value of the leaf.
     */
    public Counter64 getFrameDiscardValue() throws JNCException {
        return (Counter64)getValue("frame-discard");
    }

    /**
     * Sets the value for child leaf "frame-discard",
     * using a JNC type value.
     * @param frameDiscardValue The value to set.
     * @param frameDiscardValue used during instantiation.
     */
    public void setFrameDiscardValue(Counter64 frameDiscardValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-discard",
            frameDiscardValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "frame-discard",
     * using Java primitive values.
     * @param frameDiscardValue used during instantiation.
     */
    public void setFrameDiscardValue(BigInteger frameDiscardValue)
            throws JNCException {
        setFrameDiscardValue(new Counter64(frameDiscardValue));
    }

    /**
     * Sets the value for child leaf "frame-discard",
     * using a String value.
     * @param frameDiscardValue used during instantiation.
     */
    public void setFrameDiscardValue(String frameDiscardValue)
            throws JNCException {
        setFrameDiscardValue(new Counter64(frameDiscardValue));
    }

    /**
     * Unsets the value for child leaf "frame-discard".
     */
    public void unsetFrameDiscardValue() throws JNCException {
        delete("frame-discard");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "frame-discard" leaf will not have a value.
     */
    public void addFrameDiscard() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "frame-discard",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "frame-discard" with operation "replace".
     */
    public void markFrameDiscardReplace() throws JNCException {
        markLeafReplace("frameDiscard");
    }

    /**
     * Marks the leaf "frame-discard" with operation "merge".
     */
    public void markFrameDiscardMerge() throws JNCException {
        markLeafMerge("frameDiscard");
    }

    /**
     * Marks the leaf "frame-discard" with operation "create".
     */
    public void markFrameDiscardCreate() throws JNCException {
        markLeafCreate("frameDiscard");
    }

    /**
     * Marks the leaf "frame-discard" with operation "delete".
     */
    public void markFrameDiscardDelete() throws JNCException {
        markLeafDelete("frameDiscard");
    }

    /* Access methods for optional leaf child: "tlv-discard". */

    /**
     * Gets the value for child leaf "tlv-discard".
     * @return The value of the leaf.
     */
    public Counter64 getTlvDiscardValue() throws JNCException {
        return (Counter64)getValue("tlv-discard");
    }

    /**
     * Sets the value for child leaf "tlv-discard",
     * using a JNC type value.
     * @param tlvDiscardValue The value to set.
     * @param tlvDiscardValue used during instantiation.
     */
    public void setTlvDiscardValue(Counter64 tlvDiscardValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-discard",
            tlvDiscardValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "tlv-discard",
     * using Java primitive values.
     * @param tlvDiscardValue used during instantiation.
     */
    public void setTlvDiscardValue(BigInteger tlvDiscardValue)
            throws JNCException {
        setTlvDiscardValue(new Counter64(tlvDiscardValue));
    }

    /**
     * Sets the value for child leaf "tlv-discard",
     * using a String value.
     * @param tlvDiscardValue used during instantiation.
     */
    public void setTlvDiscardValue(String tlvDiscardValue) throws JNCException {
        setTlvDiscardValue(new Counter64(tlvDiscardValue));
    }

    /**
     * Unsets the value for child leaf "tlv-discard".
     */
    public void unsetTlvDiscardValue() throws JNCException {
        delete("tlv-discard");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "tlv-discard" leaf will not have a value.
     */
    public void addTlvDiscard() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-discard",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "tlv-discard" with operation "replace".
     */
    public void markTlvDiscardReplace() throws JNCException {
        markLeafReplace("tlvDiscard");
    }

    /**
     * Marks the leaf "tlv-discard" with operation "merge".
     */
    public void markTlvDiscardMerge() throws JNCException {
        markLeafMerge("tlvDiscard");
    }

    /**
     * Marks the leaf "tlv-discard" with operation "create".
     */
    public void markTlvDiscardCreate() throws JNCException {
        markLeafCreate("tlvDiscard");
    }

    /**
     * Marks the leaf "tlv-discard" with operation "delete".
     */
    public void markTlvDiscardDelete() throws JNCException {
        markLeafDelete("tlvDiscard");
    }

    /* Access methods for optional leaf child: "tlv-unknown". */

    /**
     * Gets the value for child leaf "tlv-unknown".
     * @return The value of the leaf.
     */
    public Counter64 getTlvUnknownValue() throws JNCException {
        return (Counter64)getValue("tlv-unknown");
    }

    /**
     * Sets the value for child leaf "tlv-unknown",
     * using a JNC type value.
     * @param tlvUnknownValue The value to set.
     * @param tlvUnknownValue used during instantiation.
     */
    public void setTlvUnknownValue(Counter64 tlvUnknownValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-unknown",
            tlvUnknownValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "tlv-unknown",
     * using Java primitive values.
     * @param tlvUnknownValue used during instantiation.
     */
    public void setTlvUnknownValue(BigInteger tlvUnknownValue)
            throws JNCException {
        setTlvUnknownValue(new Counter64(tlvUnknownValue));
    }

    /**
     * Sets the value for child leaf "tlv-unknown",
     * using a String value.
     * @param tlvUnknownValue used during instantiation.
     */
    public void setTlvUnknownValue(String tlvUnknownValue) throws JNCException {
        setTlvUnknownValue(new Counter64(tlvUnknownValue));
    }

    /**
     * Unsets the value for child leaf "tlv-unknown".
     */
    public void unsetTlvUnknownValue() throws JNCException {
        delete("tlv-unknown");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "tlv-unknown" leaf will not have a value.
     */
    public void addTlvUnknown() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-unknown",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "tlv-unknown" with operation "replace".
     */
    public void markTlvUnknownReplace() throws JNCException {
        markLeafReplace("tlvUnknown");
    }

    /**
     * Marks the leaf "tlv-unknown" with operation "merge".
     */
    public void markTlvUnknownMerge() throws JNCException {
        markLeafMerge("tlvUnknown");
    }

    /**
     * Marks the leaf "tlv-unknown" with operation "create".
     */
    public void markTlvUnknownCreate() throws JNCException {
        markLeafCreate("tlvUnknown");
    }

    /**
     * Marks the leaf "tlv-unknown" with operation "delete".
     */
    public void markTlvUnknownDelete() throws JNCException {
        markLeafDelete("tlvUnknown");
    }

    /* Access methods for optional leaf child: "last-clear". */

    /**
     * Gets the value for child leaf "last-clear".
     * @return The value of the leaf.
     */
    public DateAndTime getLastClearValue() throws JNCException {
        return (DateAndTime)getValue("last-clear");
    }

    /**
     * Sets the value for child leaf "last-clear",
     * using a JNC type value.
     * @param lastClearValue The value to set.
     * @param lastClearValue used during instantiation.
     */
    public void setLastClearValue(DateAndTime lastClearValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "last-clear",
            lastClearValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "last-clear",
     * using a String value.
     * @param lastClearValue used during instantiation.
     */
    public void setLastClearValue(String lastClearValue) throws JNCException {
        setLastClearValue(new DateAndTime(lastClearValue));
    }

    /**
     * Unsets the value for child leaf "last-clear".
     */
    public void unsetLastClearValue() throws JNCException {
        delete("last-clear");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "last-clear" leaf will not have a value.
     */
    public void addLastClear() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "last-clear",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "last-clear" with operation "replace".
     */
    public void markLastClearReplace() throws JNCException {
        markLeafReplace("lastClear");
    }

    /**
     * Marks the leaf "last-clear" with operation "merge".
     */
    public void markLastClearMerge() throws JNCException {
        markLeafMerge("lastClear");
    }

    /**
     * Marks the leaf "last-clear" with operation "create".
     */
    public void markLastClearCreate() throws JNCException {
        markLeafCreate("lastClear");
    }

    /**
     * Marks the leaf "last-clear" with operation "delete".
     */
    public void markLastClearDelete() throws JNCException {
        markLeafDelete("lastClear");
    }

    /* Access methods for optional leaf child: "tlv-accepted". */

    /**
     * Gets the value for child leaf "tlv-accepted".
     * @return The value of the leaf.
     */
    public Counter64 getTlvAcceptedValue() throws JNCException {
        return (Counter64)getValue("tlv-accepted");
    }

    /**
     * Sets the value for child leaf "tlv-accepted",
     * using a JNC type value.
     * @param tlvAcceptedValue The value to set.
     * @param tlvAcceptedValue used during instantiation.
     */
    public void setTlvAcceptedValue(Counter64 tlvAcceptedValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-accepted",
            tlvAcceptedValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "tlv-accepted",
     * using Java primitive values.
     * @param tlvAcceptedValue used during instantiation.
     */
    public void setTlvAcceptedValue(BigInteger tlvAcceptedValue)
            throws JNCException {
        setTlvAcceptedValue(new Counter64(tlvAcceptedValue));
    }

    /**
     * Sets the value for child leaf "tlv-accepted",
     * using a String value.
     * @param tlvAcceptedValue used during instantiation.
     */
    public void setTlvAcceptedValue(String tlvAcceptedValue)
            throws JNCException {
        setTlvAcceptedValue(new Counter64(tlvAcceptedValue));
    }

    /**
     * Unsets the value for child leaf "tlv-accepted".
     */
    public void unsetTlvAcceptedValue() throws JNCException {
        delete("tlv-accepted");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "tlv-accepted" leaf will not have a value.
     */
    public void addTlvAccepted() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "tlv-accepted",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "tlv-accepted" with operation "replace".
     */
    public void markTlvAcceptedReplace() throws JNCException {
        markLeafReplace("tlvAccepted");
    }

    /**
     * Marks the leaf "tlv-accepted" with operation "merge".
     */
    public void markTlvAcceptedMerge() throws JNCException {
        markLeafMerge("tlvAccepted");
    }

    /**
     * Marks the leaf "tlv-accepted" with operation "create".
     */
    public void markTlvAcceptedCreate() throws JNCException {
        markLeafCreate("tlvAccepted");
    }

    /**
     * Marks the leaf "tlv-accepted" with operation "delete".
     */
    public void markTlvAcceptedDelete() throws JNCException {
        markLeafDelete("tlvAccepted");
    }

    /* Access methods for optional leaf child: "entries-aged-out". */

    /**
     * Gets the value for child leaf "entries-aged-out".
     * @return The value of the leaf.
     */
    public Counter64 getEntriesAgedOutValue() throws JNCException {
        return (Counter64)getValue("entries-aged-out");
    }

    /**
     * Sets the value for child leaf "entries-aged-out",
     * using a JNC type value.
     * @param entriesAgedOutValue The value to set.
     * @param entriesAgedOutValue used during instantiation.
     */
    public void setEntriesAgedOutValue(Counter64 entriesAgedOutValue)
            throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "entries-aged-out",
            entriesAgedOutValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "entries-aged-out",
     * using Java primitive values.
     * @param entriesAgedOutValue used during instantiation.
     */
    public void setEntriesAgedOutValue(BigInteger entriesAgedOutValue)
            throws JNCException {
        setEntriesAgedOutValue(new Counter64(entriesAgedOutValue));
    }

    /**
     * Sets the value for child leaf "entries-aged-out",
     * using a String value.
     * @param entriesAgedOutValue used during instantiation.
     */
    public void setEntriesAgedOutValue(String entriesAgedOutValue)
            throws JNCException {
        setEntriesAgedOutValue(new Counter64(entriesAgedOutValue));
    }

    /**
     * Unsets the value for child leaf "entries-aged-out".
     */
    public void unsetEntriesAgedOutValue() throws JNCException {
        delete("entries-aged-out");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "entries-aged-out" leaf will not have a value.
     */
    public void addEntriesAgedOut() throws JNCException {
        setLeafValue(OcLldp.NAMESPACE,
            "entries-aged-out",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "entries-aged-out" with operation "replace".
     */
    public void markEntriesAgedOutReplace() throws JNCException {
        markLeafReplace("entriesAgedOut");
    }

    /**
     * Marks the leaf "entries-aged-out" with operation "merge".
     */
    public void markEntriesAgedOutMerge() throws JNCException {
        markLeafMerge("entriesAgedOut");
    }

    /**
     * Marks the leaf "entries-aged-out" with operation "create".
     */
    public void markEntriesAgedOutCreate() throws JNCException {
        markLeafCreate("entriesAgedOut");
    }

    /**
     * Marks the leaf "entries-aged-out" with operation "delete".
     */
    public void markEntriesAgedOutDelete() throws JNCException {
        markLeafDelete("entriesAgedOut");
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
