/* 
 * @(#)PortIdType.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-lldp-types", revision: "2016-05-16".
 */

package com.nokia.eml.yang.openconfigLldpTypes;

import com.tailf.jnc.YangEnumeration;
import com.tailf.jnc.YangException;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "src/com/nokia/eml/yang/openconfigLldpTypes/port-id-type"
 * <p>
 * See line 248 in
 * /root/nokia-yang/lldp/openconfig-lldp-types.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class PortIdType extends YangEnumeration {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for PortIdType object from a string.
     * @param value Value to construct the PortIdType from.
     */
    public PortIdType(String value) throws YangException {
        super(value,
            new String[] {
                "INTERFACE_ALIAS",
                "PORT_COMPONENT",
                "MAC_ADDRESS",
                "NETWORK_ADDRESS",
                "INTERFACE_NAME",
                "AGENT_CIRCUIT_ID",
                "LOCAL",
            }
        );
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
        super.check();
    }

}
