/* 
 * @(#)Temperature.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-platform", revision: "2018-06-06".
 */

package com.nokia.eml.yang.openconfigPlatform.components.component.state;

import com.nokia.eml.yang.openconfigPlatform.OcPlatform;
import com.nokia.eml.yang.openconfigPlatformTypes.OcPlatformTypes;
import com.nokia.eml.yang.openconfigTypes.StatInterval;
import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangBoolean;
import com.tailf.jnc.YangDecimal64;
import com.tailf.jnc.YangElement;
import com.tailf.jnc.YangIdentityref;
import com.tailf.jnc.YangUInt32;

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * This class represents an element from 
 * the namespace http://openconfig.net/yang/platform
 * generated to "src/com/nokia/eml/yang/openconfigPlatform/components/component/state/temperature"
 * <p>
 * See line 408 in
 * /root/nokia-yang/platform/openconfig-platform.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class Temperature extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Temperature object.
     */
    public Temperature() {
        super(OcPlatform.NAMESPACE, "temperature");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Temperature clone() {
        return (Temperature)cloneContent(new Temperature());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Temperature cloneShallow() {
        return (Temperature)cloneShallowContent(new Temperature());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "instant",
            "avg",
            "min",
            "max",
            "interval",
            "alarm-status",
            "alarm-threshold",
            "alarm-severity",
        };
    }

    /* Access methods for optional leaf child: "instant". */

    /**
     * Gets the value for child leaf "instant".
     * @return The value of the leaf.
     */
    public YangDecimal64 getInstantValue() throws JNCException {
        return (YangDecimal64)getValue("instant");
    }

    /**
     * Sets the value for child leaf "instant",
     * using instance of generated typedef class.
     * @param instantValue The value to set.
     * @param instantValue used during instantiation.
     */
    public void setInstantValue(YangDecimal64 instantValue) throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "instant",
            instantValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "instant",
     * using Java primitive values.
     * @param instantValue used during instantiation.
     */
    public void setInstantValue(BigDecimal instantValue) throws JNCException {
        setInstantValue(new YangDecimal64(instantValue, 1));
    }

    /**
     * Sets the value for child leaf "instant",
     * using a String value.
     * @param instantValue used during instantiation.
     */
    public void setInstantValue(String instantValue) throws JNCException {
        setInstantValue(new YangDecimal64(instantValue, 1));
    }

    /**
     * Unsets the value for child leaf "instant".
     */
    public void unsetInstantValue() throws JNCException {
        delete("instant");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "instant" leaf will not have a value.
     */
    public void addInstant() throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "instant",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "instant" with operation "replace".
     */
    public void markInstantReplace() throws JNCException {
        markLeafReplace("instant");
    }

    /**
     * Marks the leaf "instant" with operation "merge".
     */
    public void markInstantMerge() throws JNCException {
        markLeafMerge("instant");
    }

    /**
     * Marks the leaf "instant" with operation "create".
     */
    public void markInstantCreate() throws JNCException {
        markLeafCreate("instant");
    }

    /**
     * Marks the leaf "instant" with operation "delete".
     */
    public void markInstantDelete() throws JNCException {
        markLeafDelete("instant");
    }

    /* Access methods for optional leaf child: "avg". */

    /**
     * Gets the value for child leaf "avg".
     * @return The value of the leaf.
     */
    public YangDecimal64 getAvgValue() throws JNCException {
        return (YangDecimal64)getValue("avg");
    }

    /**
     * Sets the value for child leaf "avg",
     * using instance of generated typedef class.
     * @param avgValue The value to set.
     * @param avgValue used during instantiation.
     */
    public void setAvgValue(YangDecimal64 avgValue) throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "avg",
            avgValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "avg",
     * using Java primitive values.
     * @param avgValue used during instantiation.
     */
    public void setAvgValue(BigDecimal avgValue) throws JNCException {
        setAvgValue(new YangDecimal64(avgValue, 1));
    }

    /**
     * Sets the value for child leaf "avg",
     * using a String value.
     * @param avgValue used during instantiation.
     */
    public void setAvgValue(String avgValue) throws JNCException {
        setAvgValue(new YangDecimal64(avgValue, 1));
    }

    /**
     * Unsets the value for child leaf "avg".
     */
    public void unsetAvgValue() throws JNCException {
        delete("avg");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "avg" leaf will not have a value.
     */
    public void addAvg() throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "avg",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "avg" with operation "replace".
     */
    public void markAvgReplace() throws JNCException {
        markLeafReplace("avg");
    }

    /**
     * Marks the leaf "avg" with operation "merge".
     */
    public void markAvgMerge() throws JNCException {
        markLeafMerge("avg");
    }

    /**
     * Marks the leaf "avg" with operation "create".
     */
    public void markAvgCreate() throws JNCException {
        markLeafCreate("avg");
    }

    /**
     * Marks the leaf "avg" with operation "delete".
     */
    public void markAvgDelete() throws JNCException {
        markLeafDelete("avg");
    }

    /* Access methods for optional leaf child: "min". */

    /**
     * Gets the value for child leaf "min".
     * @return The value of the leaf.
     */
    public YangDecimal64 getMinValue() throws JNCException {
        return (YangDecimal64)getValue("min");
    }

    /**
     * Sets the value for child leaf "min",
     * using instance of generated typedef class.
     * @param minValue The value to set.
     * @param minValue used during instantiation.
     */
    public void setMinValue(YangDecimal64 minValue) throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "min",
            minValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "min",
     * using Java primitive values.
     * @param minValue used during instantiation.
     */
    public void setMinValue(BigDecimal minValue) throws JNCException {
        setMinValue(new YangDecimal64(minValue, 1));
    }

    /**
     * Sets the value for child leaf "min",
     * using a String value.
     * @param minValue used during instantiation.
     */
    public void setMinValue(String minValue) throws JNCException {
        setMinValue(new YangDecimal64(minValue, 1));
    }

    /**
     * Unsets the value for child leaf "min".
     */
    public void unsetMinValue() throws JNCException {
        delete("min");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "min" leaf will not have a value.
     */
    public void addMin() throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "min",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "min" with operation "replace".
     */
    public void markMinReplace() throws JNCException {
        markLeafReplace("min");
    }

    /**
     * Marks the leaf "min" with operation "merge".
     */
    public void markMinMerge() throws JNCException {
        markLeafMerge("min");
    }

    /**
     * Marks the leaf "min" with operation "create".
     */
    public void markMinCreate() throws JNCException {
        markLeafCreate("min");
    }

    /**
     * Marks the leaf "min" with operation "delete".
     */
    public void markMinDelete() throws JNCException {
        markLeafDelete("min");
    }

    /* Access methods for optional leaf child: "max". */

    /**
     * Gets the value for child leaf "max".
     * @return The value of the leaf.
     */
    public YangDecimal64 getMaxValue() throws JNCException {
        return (YangDecimal64)getValue("max");
    }

    /**
     * Sets the value for child leaf "max",
     * using instance of generated typedef class.
     * @param maxValue The value to set.
     * @param maxValue used during instantiation.
     */
    public void setMaxValue(YangDecimal64 maxValue) throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "max",
            maxValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "max",
     * using Java primitive values.
     * @param maxValue used during instantiation.
     */
    public void setMaxValue(BigDecimal maxValue) throws JNCException {
        setMaxValue(new YangDecimal64(maxValue, 1));
    }

    /**
     * Sets the value for child leaf "max",
     * using a String value.
     * @param maxValue used during instantiation.
     */
    public void setMaxValue(String maxValue) throws JNCException {
        setMaxValue(new YangDecimal64(maxValue, 1));
    }

    /**
     * Unsets the value for child leaf "max".
     */
    public void unsetMaxValue() throws JNCException {
        delete("max");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "max" leaf will not have a value.
     */
    public void addMax() throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "max",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "max" with operation "replace".
     */
    public void markMaxReplace() throws JNCException {
        markLeafReplace("max");
    }

    /**
     * Marks the leaf "max" with operation "merge".
     */
    public void markMaxMerge() throws JNCException {
        markLeafMerge("max");
    }

    /**
     * Marks the leaf "max" with operation "create".
     */
    public void markMaxCreate() throws JNCException {
        markLeafCreate("max");
    }

    /**
     * Marks the leaf "max" with operation "delete".
     */
    public void markMaxDelete() throws JNCException {
        markLeafDelete("max");
    }

    /* Access methods for optional leaf child: "interval". */

    /**
     * Gets the value for child leaf "interval".
     * @return The value of the leaf.
     */
    public StatInterval getIntervalValue() throws JNCException {
        return (StatInterval)getValue("interval");
    }

    /**
     * Sets the value for child leaf "interval",
     * using a JNC type value.
     * @param intervalValue The value to set.
     * @param intervalValue used during instantiation.
     */
    public void setIntervalValue(StatInterval intervalValue)
            throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "interval",
            intervalValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "interval",
     * using Java primitive values.
     * @param intervalValue used during instantiation.
     */
    public void setIntervalValue(BigInteger intervalValue) throws JNCException {
        setIntervalValue(new StatInterval(intervalValue));
    }

    /**
     * Sets the value for child leaf "interval",
     * using a String value.
     * @param intervalValue used during instantiation.
     */
    public void setIntervalValue(String intervalValue) throws JNCException {
        setIntervalValue(new StatInterval(intervalValue));
    }

    /**
     * Unsets the value for child leaf "interval".
     */
    public void unsetIntervalValue() throws JNCException {
        delete("interval");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "interval" leaf will not have a value.
     */
    public void addInterval() throws JNCException {
        setLeafValue(OcPlatformTypes.NAMESPACE,
            "interval",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "interval" with operation "replace".
     */
    public void markIntervalReplace() throws JNCException {
        markLeafReplace("interval");
    }

    /**
     * Marks the leaf "interval" with operation "merge".
     */
    public void markIntervalMerge() throws JNCException {
        markLeafMerge("interval");
    }

    /**
     * Marks the leaf "interval" with operation "create".
     */
    public void markIntervalCreate() throws JNCException {
        markLeafCreate("interval");
    }

    /**
     * Marks the leaf "interval" with operation "delete".
     */
    public void markIntervalDelete() throws JNCException {
        markLeafDelete("interval");
    }

    /* Access methods for optional leaf child: "alarm-status". */

    /**
     * Gets the value for child leaf "alarm-status".
     * @return The value of the leaf.
     */
    public YangBoolean getAlarmStatusValue() throws JNCException {
        return (YangBoolean)getValue("alarm-status");
    }

    /**
     * Sets the value for child leaf "alarm-status",
     * using instance of generated typedef class.
     * @param alarmStatusValue The value to set.
     * @param alarmStatusValue used during instantiation.
     */
    public void setAlarmStatusValue(YangBoolean alarmStatusValue)
            throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-status",
            alarmStatusValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "alarm-status",
     * using Java primitive values.
     * @param alarmStatusValue used during instantiation.
     */
    public void setAlarmStatusValue(Boolean alarmStatusValue)
            throws JNCException {
        setAlarmStatusValue(new YangBoolean(alarmStatusValue));
    }

    /**
     * Sets the value for child leaf "alarm-status",
     * using a String value.
     * @param alarmStatusValue used during instantiation.
     */
    public void setAlarmStatusValue(String alarmStatusValue)
            throws JNCException {
        setAlarmStatusValue(new YangBoolean(alarmStatusValue));
    }

    /**
     * Unsets the value for child leaf "alarm-status".
     */
    public void unsetAlarmStatusValue() throws JNCException {
        delete("alarm-status");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "alarm-status" leaf will not have a value.
     */
    public void addAlarmStatus() throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-status",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "alarm-status" with operation "replace".
     */
    public void markAlarmStatusReplace() throws JNCException {
        markLeafReplace("alarmStatus");
    }

    /**
     * Marks the leaf "alarm-status" with operation "merge".
     */
    public void markAlarmStatusMerge() throws JNCException {
        markLeafMerge("alarmStatus");
    }

    /**
     * Marks the leaf "alarm-status" with operation "create".
     */
    public void markAlarmStatusCreate() throws JNCException {
        markLeafCreate("alarmStatus");
    }

    /**
     * Marks the leaf "alarm-status" with operation "delete".
     */
    public void markAlarmStatusDelete() throws JNCException {
        markLeafDelete("alarmStatus");
    }

    /* Access methods for optional leaf child: "alarm-threshold". */

    /**
     * Gets the value for child leaf "alarm-threshold".
     * @return The value of the leaf.
     */
    public YangUInt32 getAlarmThresholdValue() throws JNCException {
        return (YangUInt32)getValue("alarm-threshold");
    }

    /**
     * Sets the value for child leaf "alarm-threshold",
     * using instance of generated typedef class.
     * @param alarmThresholdValue The value to set.
     * @param alarmThresholdValue used during instantiation.
     */
    public void setAlarmThresholdValue(YangUInt32 alarmThresholdValue)
            throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-threshold",
            alarmThresholdValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "alarm-threshold",
     * using Java primitive values.
     * @param alarmThresholdValue used during instantiation.
     */
    public void setAlarmThresholdValue(long alarmThresholdValue)
            throws JNCException {
        setAlarmThresholdValue(new YangUInt32(alarmThresholdValue));
    }

    /**
     * Sets the value for child leaf "alarm-threshold",
     * using a String value.
     * @param alarmThresholdValue used during instantiation.
     */
    public void setAlarmThresholdValue(String alarmThresholdValue)
            throws JNCException {
        setAlarmThresholdValue(new YangUInt32(alarmThresholdValue));
    }

    /**
     * Unsets the value for child leaf "alarm-threshold".
     */
    public void unsetAlarmThresholdValue() throws JNCException {
        delete("alarm-threshold");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "alarm-threshold" leaf will not have a value.
     */
    public void addAlarmThreshold() throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-threshold",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "alarm-threshold" with operation "replace".
     */
    public void markAlarmThresholdReplace() throws JNCException {
        markLeafReplace("alarmThreshold");
    }

    /**
     * Marks the leaf "alarm-threshold" with operation "merge".
     */
    public void markAlarmThresholdMerge() throws JNCException {
        markLeafMerge("alarmThreshold");
    }

    /**
     * Marks the leaf "alarm-threshold" with operation "create".
     */
    public void markAlarmThresholdCreate() throws JNCException {
        markLeafCreate("alarmThreshold");
    }

    /**
     * Marks the leaf "alarm-threshold" with operation "delete".
     */
    public void markAlarmThresholdDelete() throws JNCException {
        markLeafDelete("alarmThreshold");
    }

    /* Access methods for optional leaf child: "alarm-severity". */

    /**
     * Gets the value for child leaf "alarm-severity".
     * @return The value of the leaf.
     */
    public YangIdentityref getAlarmSeverityValue() throws JNCException {
        return (YangIdentityref)getValue("alarm-severity");
    }

    /**
     * Sets the value for child leaf "alarm-severity",
     * using instance of generated typedef class.
     * @param alarmSeverityValue The value to set.
     * @param alarmSeverityValue used during instantiation.
     */
    public void setAlarmSeverityValue(YangIdentityref alarmSeverityValue)
            throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-severity",
            alarmSeverityValue,
            childrenNames());
    }

    /**
     * Sets the value for child leaf "alarm-severity",
     * using a String value.
     * @param alarmSeverityValue used during instantiation.
     */
    public void setAlarmSeverityValue(String alarmSeverityValue)
            throws JNCException {
        setAlarmSeverityValue(new YangIdentityref(alarmSeverityValue));
    }

    /**
     * Unsets the value for child leaf "alarm-severity".
     */
    public void unsetAlarmSeverityValue() throws JNCException {
        delete("alarm-severity");
    }

    /**
     * This method is used for creating a subtree filter.
     * The added "alarm-severity" leaf will not have a value.
     */
    public void addAlarmSeverity() throws JNCException {
        setLeafValue(OcPlatform.NAMESPACE,
            "alarm-severity",
            null,
            childrenNames());
    }

    /**
     * Marks the leaf "alarm-severity" with operation "replace".
     */
    public void markAlarmSeverityReplace() throws JNCException {
        markLeafReplace("alarmSeverity");
    }

    /**
     * Marks the leaf "alarm-severity" with operation "merge".
     */
    public void markAlarmSeverityMerge() throws JNCException {
        markLeafMerge("alarmSeverity");
    }

    /**
     * Marks the leaf "alarm-severity" with operation "create".
     */
    public void markAlarmSeverityCreate() throws JNCException {
        markLeafCreate("alarmSeverity");
    }

    /**
     * Marks the leaf "alarm-severity" with operation "delete".
     */
    public void markAlarmSeverityDelete() throws JNCException {
        markLeafDelete("alarmSeverity");
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
