/* 
 * @(#)Capabilities.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-notificaions", revision: "2018-06-06".
 */

package com.nokia.eml.yang.openconfigNotificaions.lldpNotification.update.lldp.interfaces.interface_.neighbors.neighbor;

import com.nokia.eml.yang.openconfigLldp.OcLldp;
import com.nokia.eml.yang.openconfigNotificaions.lldpNotification.update.lldp.interfaces.interface_.neighbors.neighbor.capabilities.Capability;
import com.tailf.jnc.Element;
import com.tailf.jnc.ElementChildrenIterator;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.YangElement;

/**
 * This class represents an element from 
 * the namespace http://openconfig.net/yang/openconfig-notificaions
 * generated to "src/com/nokia/eml/yang/openconfigNotificaions/lldpNotification/update/lldp/interfaces/interface_/neighbors/neighbor/capabilities"
 * <p>
 * See line 287 in
 * /root/nokia-yang/lldp/openconfig-lldp.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class Capabilities extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for an empty Capabilities object.
     */
    public Capabilities() {
        super(OcLldp.NAMESPACE, "capabilities");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Capabilities clone() {
        return (Capabilities)cloneContent(new Capabilities());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Capabilities cloneShallow() {
        return (Capabilities)cloneShallowContent(new Capabilities());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "capability",
        };
    }

    /* Access methods for list child: "capability". */

    /**
     * Gets list entry "capability", with specified keys.
     */
    public Capability getCapability() throws JNCException {
        String path = "capability";
        return (Capability)searchOne(path);
    }

    /**
     * Iterator method for the list "capability".
     * @return An iterator for the list.
     */
    public ElementChildrenIterator capabilityIterator() {
        return new ElementChildrenIterator(children, "capability");
    }

    /**
     * Adds list entry "capability", using an existing object.
     * @param capability The object to add.
     * @return The added child.
     */
    public Capability addCapability(Capability capability) throws JNCException {
        insertChild(capability, childrenNames());
        return capability;
    }

    /**
     * Adds list entry "capability".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public Capability addCapability() throws JNCException {
        Capability capability = new Capability();
        insertChild(capability, childrenNames());
        return capability;
    }

    /**
     * Deletes list entry "capability", with specified keys.
     */
    public void deleteCapability() throws JNCException {
        String path = "capability";
        delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
    }

}
