/* 
 * @(#)JIf.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "ietf-interfaces", revision: "2018-02-20".
 */

package com.nokia.eml.yang.ietfInterfaces;

import com.tailf.jnc.JNCException;
import com.tailf.jnc.SchemaNode;
import com.tailf.jnc.SchemaParser;
import com.tailf.jnc.SchemaTree;
import com.tailf.jnc.Tagpath;
import com.tailf.jnc.YangElement;

import java.util.HashMap;

/**
 * The root class for namespace urn:ietf:params:xml:ns:yang:ietf-interfaces (accessible from 
 * IetfInterfaces.NAMESPACE) with prefix "if" (IetfInterfaces.PREFIX).
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class JIf {

    public static final String NAMESPACE = "urn:ietf:params:xml:ns:yang:ietf-interfaces";

    public static final String PREFIX = "if";

    /**
     * Enable the elements in this namespace to be aware
     * of the data model and use the generated classes.
     */
    public static void enable() throws JNCException {
        YangElement.setPackage(NAMESPACE, "com.nokia.eml.yang.ietfInterfaces");
        JIf.registerSchema();
    }

    /**
     * Register the schema for this namespace in the global
     * schema table (CsTree) making it possible to lookup
     * CsNode entries for all tagpaths
     */
    public static void registerSchema() throws JNCException {
        SchemaParser parser = new SchemaParser();
        HashMap<Tagpath, SchemaNode> h = SchemaTree.create(NAMESPACE);
        parser.findAndReadFile("JIf.schema", h, JIf.class);
    }

}
