/* 
 * @(#)Update.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-notificaions", revision: "2018-06-06".
 */

package com.nokia.eml.yang.openconfigNotificaions.alarmNotification;

import com.nokia.eml.yang.openconfigNotificaions.OcNotify;
import com.nokia.eml.yang.openconfigNotificaions.alarmNotification.update.System;
import com.tailf.jnc.Element;
import com.tailf.jnc.JNCException;
import com.tailf.jnc.NodeSet;
import com.tailf.jnc.YangElement;

/**
 * This class represents an element from 
 * the namespace http://openconfig.net/yang/openconfig-notificaions
 * generated to "src/com/nokia/eml/yang/openconfigNotificaions/alarmNotification/update"
 * <p>
 * See line 74 in
 * /root/nokia-yang/openconfig-notificaions.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class Update extends YangElement {

    private static final long serialVersionUID = 1L;

    /**
     * Field for child container "system".
     */
    public System system = null;

    /**
     * Constructor for an empty Update object.
     */
    public Update() {
        super(OcNotify.NAMESPACE, "update");
    }

    /**
     * Clones this object, returning an exact copy.
     * @return A clone of the object.
     */
    public Update clone() {
        return (Update)cloneContent(new Update());
    }

    /**
     * Clones this object, returning a shallow copy.
     * @return A clone of the object. Children are not included.
     */
    public Update cloneShallow() {
        return (Update)cloneShallowContent(new Update());
    }

    /**
     * @return An array with the identifiers of any key children
     */
    public String[] keyNames() {
        return null;
    }

    /**
     * @return An array with the identifiers of any children, in order.
     */
    public String[] childrenNames() {
        return new String[] {
            "system",
        };
    }

    /* Access methods for container child: "system". */

    /**
     * Adds container entry "system", using an existing object.
     * @param system The object to add.
     * @return The added child.
     */
    public System addSystem(System system) throws JNCException {
        this.system = system;
        insertChild(system, childrenNames());
        return system;
    }

    /**
     * Adds container entry "system".
     * This method is used for creating subtree filters.
     * @return The added child.
     */
    public System addSystem() throws JNCException {
        System system = new System();
        this.system = system;
        insertChild(system, childrenNames());
        return system;
    }

    /**
     * Deletes container entry "system".
     * @return An array of the deleted element nodes.
     */
    public NodeSet deleteSystem() throws JNCException {
        this.system = null;
        String path = "system";
        return delete(path);
    }

    /**
     * Support method for addChild.
     * Adds a child to this object.
     * 
     * @param child The child to add
     */
    public void addChild(Element child) {
        super.addChild(child);
        if (child instanceof System) system = (System)child;
    }

}
