/* 
 * @(#)StatInterval.java        1.0 15/06/18
 *
 * This file has been auto-generated by JNC, the
 * Java output format plug-in of pyang.
 * Origin: module "openconfig-types", revision: "2018-01-16".
 */

package com.nokia.eml.yang.openconfigTypes;

import com.tailf.jnc.YangException;
import com.tailf.jnc.YangUInt64;

import java.math.BigInteger;

/**
 * This class represents an element from 
 * the namespace 
 * generated to "src/com/nokia/eml/yang/openconfigTypes/stat-interval"
 * <p>
 * See line 121 in
 * /root/nokia-yang/types/openconfig-types.yang
 *
 * @version 1.0 2018-06-15
 * @author Auto Generated
 */
public class StatInterval extends YangUInt64 {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor for StatInterval object from a string.
     * @param value Value to construct the StatInterval from.
     */
    public StatInterval(String value) throws YangException {
        super(value);
        check();
    }

    /**
     * Constructor for StatInterval object from a BigInteger.
     * @param value Value to construct the StatInterval from.
     */
    public StatInterval(BigInteger value) throws YangException {
        super(value);
        check();
    }

    /**
     * Sets the value using a string value.
     * @param value The value to set.
     */
    public void setValue(String value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Sets the value using a value of type BigInteger.
     * @param value The value to set.
     */
    public void setValue(BigInteger value) throws YangException {
        super.setValue(value);
        check();
    }

    /**
     * Checks all restrictions (if any).
     */
    public void check() throws YangException {
    }

}
